### ISSUE TITLE
When searching, display numbers in descending order

### ISSUE THREAD

**Issue by cauebs** [neurobin/pacget#1]
Something I quite like about [yay](https://github.com/Jguer/yay) is that when you search it displays the normal repo packages after the aur packages (and pacget already does that).

In my opinion this could be improved even more by displaying the indices in descending order, making the last shown package be 1, or maybe 0 (which is what yay also does).

What are your thoughts on this?

**Comment by neurobin** [comment]
Nice idea, that would make the numbering more meaningful. I shall add this in next update.

**Comment by neurobin** [comment]
done
