### ISSUE TITLE
Result spacing - bug: first result lacks spacing, feature request: can spacing be toggled?

### ISSUE THREAD

**Issue by mxmilkiib** [neurobin/pacget#3]
![silver_2017-10-27-31](https://user-images.githubusercontent.com/108225/32093148-3b27773e-baf3-11e7-837a-61f71a9712dc.png)

![silver_2017-10-27-14](https://user-images.githubusercontent.com/108225/32093316-bb272dbc-baf3-11e7-9002-21e04c07caf4.png)

I'm also wondering if it might be possible to add an option to disable spacing? I would prefer to have more information visible and just use the colours to distinguish entries. Thanks for your time.

**Comment by neurobin** [comment]
done.

**Comment by mxmilkiib** [comment]
Thanks very much! Could it be made that -c also removes the double line space after the results?

![silver_2017-10-29-40](https://user-images.githubusercontent.com/108225/32146914-4d1c831e-bcd6-11e7-8b08-ded5a7dabcf0.png)

**Comment by neurobin** [comment]
removed the double spacing in compact mode. Thanks for the suggestion
