### ISSUE TITLE
Unofficial user repositories not processed in search results

### ISSUE THREAD

**Issue by mxmilkiib** [neurobin/pacget#6]
![silver_2017-11-07-15](https://user-images.githubusercontent.com/108225/32521243-aef5f814-c40a-11e7-9eff-047282f58545.png)

Also, further up after repo-ck/, there was one more properly done community/, then the aur/ results. Would it be possible for unofficial repos to come after aur/?

**Comment by neurobin** [comment]
Can you post  shorthand commands to reproduce this error quickly?

**Comment by mxmilkiib** [comment]
Stick an unofficial repo in pacman.conf, i.e.

```
[repo-ck]
Server = http://repo-ck.com/$arch
SigLevel = Never
```

$ pacget -Sy

$ pacget -Ss i3
